mod 'puppet/ngnix', '1.0.0'
mod 'puppetlabs/stdlib'
mod 'puppetlabs/concat'
mod 'puppetlabs/translate'
mod 'puppetlabs/powershell'
mod 'puppetlabs/reboot'
mod 'samuelson/dockeragent'
mod 'puppetlabs/docker'
